config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clarvia-org/clarvia-graph:
      branch: main
      repo: https://github.com/clarvia-org/clarvia-graph
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clarvia-org/clarvia-graph git:
        commands:
        - /usr/bin/env sh .sqa/script.plum_patient_dolphin.sh
        container: qc.acc_malachite_brave_rabbit
  QC.Doc:
    repos:
      github.com/clarvia-org/clarvia-graph find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.eggplant_methodical_toucan.sh
        container: qc.doc_flint_mindful_otter
      github.com/clarvia-org/clarvia-graph git:
        commands:
        - /usr/bin/env sh .sqa/script.zinnia_gracious_dugong.sh
        container: qc.doc_snow_eager_panda
      github.com/clarvia-org/clarvia-graph markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.fern_vibrant_grasshopper.sh
        container: qc.doc_cinnabar_diligent_seahorse
  QC.Lic:
    repos:
      github.com/clarvia-org/clarvia-graph licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slate_graceful_ferret.sh
        container: qc.lic_flax_logical_phoenix
  QC.Met:
    repos:
      github.com/clarvia-org/clarvia-graph cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cinnamon_thoughtful_horse.sh
        container: qc.met_indigo_melancholy_stingray
  QC.Sty:
    repos:
      github.com/clarvia-org/clarvia-graph jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.obsidian_proactive_sphinx.sh
        container: qc.sty_amaranth_elated_butterfly
  QC.Ver:
    repos:
      github.com/clarvia-org/clarvia-graph get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.champagne_clever_axolotl.sh
        container: qc.ver_harlequin_humble_emu
timeout: 5400
