config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/clarvia-org/clarvia-graph:
      branch: main
      repo: https://github.com/clarvia-org/clarvia-graph
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/clarvia-org/clarvia-graph git:
        commands:
        - /usr/bin/env sh .sqa/script.espresso_hardworking_tiger.sh
        container: qc.acc_purple_optimistic_eagle
  QC.Doc:
    repos:
      github.com/clarvia-org/clarvia-graph find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.prussian_humble_ibex.sh
        container: qc.doc_linen_silly_goat
      github.com/clarvia-org/clarvia-graph git:
        commands:
        - /usr/bin/env sh .sqa/script.khaki_amiable_echidna.sh
        container: qc.doc_byzantium_devoted_python
      github.com/clarvia-org/clarvia-graph markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cardamom_understanding_cougar.sh
        container: qc.doc_thistle_determined_osprey
  QC.Lic:
    repos:
      github.com/clarvia-org/clarvia-graph licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hunter_sincere_tapir.sh
        container: qc.lic_ruby_humble_termite
  QC.Met:
    repos:
      github.com/clarvia-org/clarvia-graph cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.denim_realistic_hummingbird.sh
        container: qc.met_violet_perky_osprey
  QC.Sty:
    repos:
      github.com/clarvia-org/clarvia-graph jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_generous_hydra.sh
        container: qc.sty_pine_insightful_lobster
  QC.Ver:
    repos:
      github.com/clarvia-org/clarvia-graph get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jet_dizzy_eagle.sh
        container: qc.ver_currant_tenacious_crane
timeout: 5400
